# DO NOT EDIT IT MANUALLY, this file was autogenerated from `raiden.rb.template`.
# Any changes made will be overwritten.

class Raiden < Formula
  desc "Raiden Network"
  homepage "https://github.com/raiden-network/homebrew-raiden"
  url "https://github.com/raiden-network/raiden/releases/download/v2.0.0/raiden-v2.0.0-macOS-x86_64.zip"
  version "v2.0.0"
  sha256 "42927308dce661ef2186559300945591ff66647f97fd2af22e2828a7815a2a14"

  depends_on :macos => :el_capitan

  def install
    mv "raiden-v2.0.0-macOS-x86_64", "raiden"
    bin.install "raiden"
  end

  test do
    system "#{bin}/raiden", "version"
  end
end
