# DO NOT EDIT IT MANUALLY, this file was autogenerated from `raiden.rb.template`.
# Any changes made will be overwritten.

class Raiden < Formula
  desc "Raiden Network"
  homepage "https://github.com/raiden-network/homebrew-raiden"
  url "https://github.com/raiden-network/raiden/releases/download/v2.0.0rc4/raiden-v2.0.0rc4-macOS-x86_64.zip"
  version "v2.0.0rc4"
  sha256 "20a91027df090e3b0eedeea998e2ea2efaf7e3c9134c1f3612a3aea0e172753e"

  depends_on :macos => :el_capitan

  def install
    mv "raiden-v2.0.0rc4-macOS-x86_64", "raiden"
    bin.install "raiden"
  end

  test do
    system "#{bin}/raiden", "version"
  end
end
