# DO NOT EDIT IT MANUALLY, this file was autogenerated from `raiden.rb.template`.
# Any changes made will be overwritten.

class Raiden < Formula
  desc "Raiden Network"
  homepage "https://github.com/raiden-network/homebrew-raiden"
  url "https://github.com/raiden-network/raiden/releases/download/v2.0.0-a0/raiden-v2.0.0-a0-macOS-x86_64.zip"
  version "v2.0.0-a0"
  sha256 "d9319cd67aa26815bf8ea7323eaeab2c27ef8340c2a07bd12a439f5298e41f92"

  depends_on :macos => :el_capitan

  def install
    mv "raiden-v2.0.0-a0-macOS-x86_64", "raiden"
    bin.install "raiden"
  end

  test do
    system "#{bin}/raiden", "version"
  end
end
